# Generated by Django 3.0.6 on 2020-06-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200601_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detailed_description',
            field=models.TextField(default='detailed description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='website_link',
            field=models.CharField(default='https://google.com', max_length=50),
            preserve_default=False,
        ),
    ]
