# Generated by Django 3.0.7 on 2020-10-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20201004_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
