# Generated by Django 3.0.7 on 2020-10-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20201004_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='website_number',
        ),
    ]
